import type {
  CatalogGame,
  CatalogStation,
  CatalogTeam,
  Conference,
  League,
  Sport,
} from "@/types/catalog";

/**
 * In-memory seed for the PlayDelay catalog. This mirrors the final database
 * tables (sports, leagues, conferences, teams, stations, games) so the UI is
 * fully data-driven today and can swap to Supabase later without UI changes.
 *
 * Station IDs/URLs intentionally match the MVP seed in `lib/data.ts` so the
 * existing player keeps working while the rest of the platform reads from here.
 */

export const SPORTS: Sport[] = [
  { id: "s-cfb", slug: "college-football", name: "College Football" },
  { id: "s-cbb", slug: "college-basketball", name: "College Basketball" },
  { id: "s-nfl", slug: "nfl", name: "NFL" },
  { id: "s-nba", slug: "nba", name: "NBA" },
];

export const LEAGUES: League[] = [
  { id: "l-ncaaf", slug: "ncaaf", name: "NCAA Football", sportId: "s-cfb" },
  { id: "l-ncaab", slug: "ncaab", name: "NCAA Basketball", sportId: "s-cbb" },
  { id: "l-nfl", slug: "nfl", name: "National Football League", sportId: "s-nfl" },
  { id: "l-nba", slug: "nba", name: "National Basketball Association", sportId: "s-nba" },
];

export const CONFERENCES: Conference[] = [
  { id: "c-big12-f", slug: "big-12-football", name: "Big 12", leagueId: "l-ncaaf" },
  { id: "c-acc-bb", slug: "acc-basketball", name: "ACC", leagueId: "l-ncaab" },
  { id: "c-big12-bb", slug: "big-12-basketball", name: "Big 12", leagueId: "l-ncaab" },
  { id: "c-afc-west", slug: "afc-west", name: "AFC West", leagueId: "l-nfl" },
  { id: "c-afc-east", slug: "afc-east", name: "AFC East", leagueId: "l-nfl" },
  { id: "c-pacific", slug: "pacific", name: "Pacific", leagueId: "l-nba" },
];

export const CATALOG_STATIONS: CatalogStation[] = [
  {
    id: "ksl-1160",
    name: "KSL 1160 AM",
    streamUrl: "https://bonneville.cdnstream1.com/2704_48.aac",
    frequency: "1160 AM",
    market: "Salt Lake City, UT",
    type: "official",
    format: "AAC",
    health: {
      status: "healthy",
      latency: "low",
      delayCompatible: true,
      score: 96,
      lastTestedAt: "2026-06-25T18:00:00.000Z",
    },
  },
  {
    id: "620-the-buzz",
    name: "620 AM The Buzz",
    streamUrl: "http://ais-sa8.cdnstream1.com/2751_64.aac",
    frequency: "620 AM",
    market: "Salt Lake City, UT",
    type: "backup",
    format: "AAC",
    health: {
      status: "warning",
      latency: "medium",
      delayCompatible: true,
      score: 71,
      lastTestedAt: "2026-06-25T17:40:00.000Z",
    },
  },
  {
    id: "espn-radio",
    name: "ESPN Radio",
    streamUrl: "https://stream.revma.ihrhls.com/zc181",
    frequency: "National",
    market: "USA",
    type: "national",
    format: "AAC",
    health: {
      status: "healthy",
      latency: "medium",
      delayCompatible: true,
      score: 90,
      lastTestedAt: "2026-06-25T18:05:00.000Z",
    },
  },
  {
    id: "espn-700-utah",
    name: "ESPN 700",
    streamUrl: "https://stream.revma.ihrhls.com/zc185",
    frequency: "700 AM",
    market: "Salt Lake City, UT",
    type: "official",
    format: "MP3",
    health: {
      status: "healthy",
      latency: "low",
      delayCompatible: true,
      score: 93,
      lastTestedAt: "2026-06-25T17:55:00.000Z",
    },
  },
  {
    id: "arizona-1290",
    name: "ESPN 1290 Tucson",
    streamUrl: "https://stream.revma.ihrhls.com/zc191",
    frequency: "1290 AM",
    market: "Tucson, AZ",
    type: "official",
    format: "MP3",
    health: {
      status: "warning",
      latency: "high",
      delayCompatible: true,
      score: 64,
      lastTestedAt: "2026-06-25T16:30:00.000Z",
    },
  },
  {
    id: "az-620",
    name: "Sun Devils 620",
    streamUrl: "https://stream.example.com/asu-620",
    frequency: "620 AM",
    market: "Phoenix, AZ",
    type: "official",
    format: "Unknown",
    health: {
      status: "broken",
      latency: "unknown",
      delayCompatible: false,
      score: 18,
      lastTestedAt: "2026-06-25T15:10:00.000Z",
    },
  },
  {
    id: "duke-gsr",
    name: "Blue Devils Sports Radio",
    streamUrl: "https://playerservices.streamtheworld.com/api/livestream-redirect/DUKEHLS.m3u8",
    frequency: "HLS",
    market: "Durham, NC",
    type: "official",
    format: "HLS",
    health: {
      status: "cors-blocked",
      latency: "medium",
      delayCompatible: false,
      score: 48,
      lastTestedAt: "2026-06-25T17:20:00.000Z",
    },
  },
  {
    id: "unc-1360",
    name: "WCHL 1360 AM",
    streamUrl: "https://stream.revma.ihrhls.com/zc197",
    frequency: "1360 AM",
    market: "Chapel Hill, NC",
    type: "official",
    format: "AAC",
    health: {
      status: "healthy",
      latency: "low",
      delayCompatible: true,
      score: 94,
      lastTestedAt: "2026-06-25T18:02:00.000Z",
    },
  },
  {
    id: "westwood-one-nfl",
    name: "Westwood One NFL",
    streamUrl: "https://stream.revma.ihrhls.com/zc200",
    frequency: "National",
    market: "USA",
    type: "national",
    format: "AAC",
    health: {
      status: "healthy",
      latency: "medium",
      delayCompatible: true,
      score: 88,
      lastTestedAt: "2026-06-25T18:01:00.000Z",
    },
  },
  {
    id: "lakers-am570",
    name: "AM 570 LA Sports",
    streamUrl: "https://stream.revma.ihrhls.com/zc205",
    frequency: "570 AM",
    market: "Los Angeles, CA",
    type: "official",
    format: "MP3",
    health: {
      status: "healthy",
      latency: "low",
      delayCompatible: true,
      score: 91,
      lastTestedAt: "2026-06-25T17:48:00.000Z",
    },
  },
];

export const CATALOG_TEAMS: CatalogTeam[] = [
  {
    id: "byu-cougars",
    slug: "byu-cougars",
    name: "BYU Cougars",
    shortName: "BYU",
    market: "Provo, UT",
    sportId: "s-cfb",
    leagueId: "l-ncaaf",
    conferenceId: "c-big12-f",
    color: "#0062B8",
    stationIds: ["ksl-1160", "620-the-buzz"],
    popular: true,
  },
  {
    id: "utah-utes",
    slug: "utah-utes",
    name: "Utah Utes",
    shortName: "Utah",
    market: "Salt Lake City, UT",
    sportId: "s-cfb",
    leagueId: "l-ncaaf",
    conferenceId: "c-big12-f",
    color: "#CC0000",
    stationIds: ["espn-700-utah", "620-the-buzz"],
  },
  {
    id: "arizona-wildcats",
    slug: "arizona-wildcats",
    name: "Arizona Wildcats",
    shortName: "Arizona",
    market: "Tucson, AZ",
    sportId: "s-cfb",
    leagueId: "l-ncaaf",
    conferenceId: "c-big12-f",
    color: "#0C234B",
    stationIds: ["arizona-1290"],
  },
  {
    id: "arizona-state-sun-devils",
    slug: "arizona-state-sun-devils",
    name: "Arizona State Sun Devils",
    shortName: "ASU",
    market: "Tempe, AZ",
    sportId: "s-cfb",
    leagueId: "l-ncaaf",
    conferenceId: "c-big12-f",
    color: "#8C1D40",
    stationIds: ["az-620"],
  },
  {
    id: "duke-blue-devils",
    slug: "duke-blue-devils",
    name: "Duke Blue Devils",
    shortName: "Duke",
    market: "Durham, NC",
    sportId: "s-cbb",
    leagueId: "l-ncaab",
    conferenceId: "c-acc-bb",
    color: "#003087",
    stationIds: ["duke-gsr", "espn-radio"],
    popular: true,
  },
  {
    id: "north-carolina-tar-heels",
    slug: "north-carolina-tar-heels",
    name: "North Carolina Tar Heels",
    shortName: "UNC",
    market: "Chapel Hill, NC",
    sportId: "s-cbb",
    leagueId: "l-ncaab",
    conferenceId: "c-acc-bb",
    color: "#4B9CD3",
    stationIds: ["unc-1360", "espn-radio"],
  },
  {
    id: "byu-cougars-bb",
    slug: "byu-cougars-basketball",
    name: "BYU Cougars (Basketball)",
    shortName: "BYU",
    market: "Provo, UT",
    sportId: "s-cbb",
    leagueId: "l-ncaab",
    conferenceId: "c-big12-bb",
    color: "#0062B8",
    stationIds: ["ksl-1160"],
  },
  {
    id: "kansas-city-chiefs",
    slug: "kansas-city-chiefs",
    name: "Kansas City Chiefs",
    shortName: "Chiefs",
    market: "Kansas City, MO",
    sportId: "s-nfl",
    leagueId: "l-nfl",
    conferenceId: "c-afc-west",
    color: "#E31837",
    stationIds: ["westwood-one-nfl", "espn-radio"],
    popular: true,
  },
  {
    id: "buffalo-bills",
    slug: "buffalo-bills",
    name: "Buffalo Bills",
    shortName: "Bills",
    market: "Buffalo, NY",
    sportId: "s-nfl",
    leagueId: "l-nfl",
    conferenceId: "c-afc-east",
    color: "#00338D",
    stationIds: ["westwood-one-nfl"],
  },
  {
    id: "los-angeles-lakers",
    slug: "los-angeles-lakers",
    name: "Los Angeles Lakers",
    shortName: "Lakers",
    market: "Los Angeles, CA",
    sportId: "s-nba",
    leagueId: "l-nba",
    conferenceId: "c-pacific",
    color: "#552583",
    stationIds: ["lakers-am570", "espn-radio"],
    popular: true,
  },
  {
    id: "golden-state-warriors",
    slug: "golden-state-warriors",
    name: "Golden State Warriors",
    shortName: "Warriors",
    market: "San Francisco, CA",
    sportId: "s-nba",
    leagueId: "l-nba",
    conferenceId: "c-pacific",
    color: "#1D428A",
    stationIds: ["espn-radio"],
  },
];

export const CATALOG_GAMES: CatalogGame[] = [
  {
    id: "g-byu-utah",
    sportId: "s-cfb",
    leagueId: "l-ncaaf",
    homeTeamId: "byu-cougars",
    awayTeamId: "utah-utes",
    startTime: "2026-06-26T01:00:00.000Z",
    network: "ESPN",
    status: "scheduled",
    highDemand: true,
  },
  {
    id: "g-ariz-asu",
    sportId: "s-cfb",
    leagueId: "l-ncaaf",
    homeTeamId: "arizona-state-sun-devils",
    awayTeamId: "arizona-wildcats",
    startTime: "2026-06-26T03:30:00.000Z",
    network: "FOX",
    status: "scheduled",
  },
  {
    id: "g-duke-unc",
    sportId: "s-cbb",
    leagueId: "l-ncaab",
    homeTeamId: "duke-blue-devils",
    awayTeamId: "north-carolina-tar-heels",
    startTime: "2026-06-26T00:00:00.000Z",
    network: "ESPN",
    status: "scheduled",
    highDemand: true,
  },
  {
    id: "g-chiefs-bills",
    sportId: "s-nfl",
    leagueId: "l-nfl",
    homeTeamId: "kansas-city-chiefs",
    awayTeamId: "buffalo-bills",
    startTime: "2026-06-28T20:25:00.000Z",
    network: "CBS",
    status: "scheduled",
    highDemand: true,
  },
  {
    id: "g-lakers-warriors",
    sportId: "s-nba",
    leagueId: "l-nba",
    homeTeamId: "los-angeles-lakers",
    awayTeamId: "golden-state-warriors",
    startTime: "2026-06-25T23:30:00.000Z",
    network: "TNT",
    status: "live",
  },
];
